version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: ./flask/Dockerfile.prod # Adjust the name if your production Dockerfile has a different name
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - internal
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:4.4.19
    environment:
      - NEO4J_AUTH=neo4j/4Jyn#WvW3H*64eH
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ../neo4j/dbms:/data/dbms
    networks:
      - internal

networks:
  internal: