# Use the specified image
FROM python:3.11-alpine

# Upgrade pip and install necessary tools (e.g., curl)
RUN pip install --upgrade pip
RUN apk add curl

# Create a non-root user for added security
RUN adduser -D nonroot

# Set the home directory for the non-root user
ENV HOME=/home/nonroot

# Set ownership for the home directory
RUN chown nonroot:nonroot $HOME

# Create /workspace directory and set ownership
RUN mkdir /workspace
RUN chown nonroot:nonroot /workspace

# Create log directories aand change ownership
RUN mkdir -p /var/log/flask-app && touch /var/log/flask-app/flask-app.err.log && touch /var/log/flask-app/flask-app.out.log
RUN chown -R nonroot:nonroot /var/log/flask-app

# Set the working directory
WORKDIR /workspace

# Python setup
ENV FLASK_APP=app.py

# Copy the requirements.txt file into the container
COPY flask/requirements.txt /workspace/requirements.txt

# Install the Python dependencies as root
RUN pip install --no-cache-dir -r /workspace/requirements.txt

# Switch to nonroot user
USER nonroot

# Print permissions for debugging
RUN ls -ld $HOME

# Define the port number the container should expose
EXPOSE 5000

# Command to idle
CMD ["tail", "-f", "/dev/null"]
