# Use the specified image
FROM python:3.11-alpine

# Upgrade pip and install necessary tools (e.g., curl)
RUN pip install --upgrade pip
RUN apk add curl

# Create a non-root user for added security
RUN adduser -D nonroot

# Create directories and set appropriate permissions
RUN mkdir /workspace && chown -R nonroot:nonroot /workspace
RUN mkdir -p /var/log/flask-app && touch /var/log/flask-app/flask-app.err.log && touch /var/log/flask-app/flask-app.out.log
RUN chown -R nonroot:nonroot /var/log/flask-app

# Set the working directory
WORKDIR /workspace

# Switch to non-root user
USER nonroot

# Copy all the files to the container
#COPY --chown=nonroot:nonroot . .
#COPY --chown=nonroot:nonroot ../flask/requirements.txt ./requirements.txt


# Set up a virtual environment
ENV VIRTUAL_ENV=/workspace/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Python setup
RUN export FLASK_APP=app.py
#RUN pip install -r requirements.txt

# Define the port number the container should expose
EXPOSE 5000

# Command to idle
CMD ["tail", "-f", "/dev/null"]
