FROM python:3.11-alpine

# Add the test script to the container
COPY test.py /workspace/test.py

# Set the working directory
WORKDIR /workspace

# Set the command to run the script
CMD ["python", "test.py"]
